INSERT INTO exercises (id, lesson_id, question_text, question_ar, question_en, question_ru, arabic_text, transliteration, translation, translation_en, translation_ru, question_type, audio_url, options_json, correct_answer, explanation, explanation_ar, explanation_en, explanation_ru, order_index) VALUES
(
  'e1000000-0001-0000-0000-000000000001',
  '10000000-0002-0000-0000-000000000001',
  'استمع إلى تحية أحمد في حوار الدرس الأول من (التحفة الأزهرية): ما هو الرد المطابق المسموع؟',
  'استمع إلى تحية أحمد في حوار الدرس الأول من (التحفة الأزهرية): ما هو الرد المطابق المسموع؟',
  'Listen to Ahmed''s greeting in Lesson 1 of Al-Tuhfa: What is the exact matching response?',
  'Послушайте приветствие Ахмеда в Уроке 1 книги «Ат-Тухфа»: Каков точный ответ?',
  'السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ',
  'As-salamu alaykum wa rahmatullahi wa barakatuh',
  'Peace be upon you and the mercy of Allah and His blessings',
  'Peace be upon you and the mercy of Allah and His blessings',
  'Мир вам, милость Аллаха и Его благословение',
  'audio_mcq',
  '/audio/tuhfa/salam_full.mp3',
  '[{"id": "opt1", "text": "وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ", "transliteration": "Wa alaykumus-salam wa rahmatullah", "text_en": "And upon you be peace and Allah''s mercy", "text_ru": "И вам мир и милость Аллаха"}, {"id": "opt2", "text": "أَهْلاً وَسَهْلاً بِكَ", "transliteration": "Ahlan wa sahlan bik", "text_en": "Welcome to you", "text_ru": "Добро пожаловать"}, {"id": "opt3", "text": "إِلَى اللِّقَاءِ يَا أَخِي", "transliteration": "Ila al-liqa'' ya akhi", "text_en": "See you later, brother", "text_ru": "До встречи, брат"}, {"id": "opt4", "text": "صَبَاحُ الخَيْرِ وَالنُّورِ", "transliteration": "Sabah al-khayr", "text_en": "Good morning", "text_ru": "Доброе утро"}]'::jsonb,
  'opt1',
  'في حوار الدرس الأول (التحفة الأزهرية): رد بلال هو: وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ.',
  'في حوار الدرس الأول (التحفة الأزهرية): رد بلال هو: وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ.',
  'In Lesson 1 dialogue (Al-Tuhfa): Bilal replies: Wa alaykumus-salam wa rahmatullahi wa barakatuh.',
  'В диалоге 1-го урока («Ат-Тухфа»): Биляль отвечает: «Ва алейкумус-салям ва рахматуллахи ва баракатух».',
  1
),
(
  'e1000000-0001-0000-0000-000000000002',
  '10000000-0002-0000-0000-000000000001',
  'سأل أحمد: (لِمَاذَا جِئْتَ إِلَى مِصْرَ؟) - ماذا أجاب بلال في كتاب التحفة الأزهرية؟',
  'سأل أحمد: (لِمَاذَا جِئْتَ إِلَى مِصْرَ؟) - ماذا أجاب بلال في كتاب التحفة الأزهرية؟',
  'Ahmed asked: (Why did you come to Egypt?) - What was Bilal''s response in Al-Tuhfa?',
  'Ахмед спросил: (Зачем ты приехал в Египет?) - Что ответил Биляль в книге «Ат-Тухфа»?',
  'لِمَاذَا جِئْتَ إِلَى مِصْرَ؟',
  'Limadha ji''ta ila Misr?',
  'Why did you come to Egypt?',
  'Why did you come to Egypt?',
  'Зачем ты приехал в Египет?',
  'audio_mcq',
  '/audio/tuhfa/limadha_jita.mp3',
  '[{"id": "opt1", "text": "لِأَتَعَلَّمَ فِي الأَزْهَرِ الشَّرِيفِ", "transliteration": "Li-ata''allama fil-Azhar ash-Sharif", "text_en": "To study at Al-Azhar Al-Sharif", "text_ru": "Чтобы учиться в благородном Аль-Азхаре"}, {"id": "opt2", "text": "لِزِيَارَةِ الأَهْرَامَاتِ", "transliteration": "Li-ziyaratil-ahramat", "text_en": "To visit the Pyramids", "text_ru": "Чтобы посетить пирамиды"}, {"id": "opt3", "text": "لِلْعَمَلِ فِي التِّجَارَةِ", "transliteration": "Lil-''amali fit-tijarah", "text_en": "To work in commerce", "text_ru": "Для работы в торговле"}, {"id": "opt4", "text": "لِلْعِلَاجِ فِي المُسْتَشْفَى", "transliteration": "Lil-''ilaj", "text_en": "For medical treatment", "text_ru": "Для лечения"}]'::jsonb,
  'opt1',
  'أجاب بلال: (لِأَتَعَلَّمَ فِي الأَزْهَرِ الشَّرِيفِ)، وهو الهدف السامي لدارسي سلسلة التحفة الأزهرية.',
  'أجاب بلال: (لِأَتَعَلَّمَ فِي الأَزْهَرِ الشَّرِيفِ)، وهو الهدف السامي لدارسي سلسلة التحفة الأزهرية.',
  'Bilal answered: (To study at Al-Azhar Al-Sharif), the primary goal of students of this series.',
  'Биляль ответил: «Чтобы учиться в благородном Аль-Азхаре».',
  2
),
(
  'e1000000-0001-0000-0000-000000000003',
  '10000000-0002-0000-0000-000000000001',
  'استمع إلى التعريف بالجنسيات والبلدان: من أين أحمد وبلال؟',
  'استمع إلى التعريف بالجنسيات والبلدان: من أين أحمد وبلال؟',
  'Listen to countries & origins: Where are Ahmed and Bilal from?',
  'Послушайте представление стран: Откуда Ахмед и Биляль?',
  'أَنَا أَحْمَدُ مِنْ أَلْمَانْيَا، وَأَنَا بِلَالٌ مِنْ بَاكِسْتَانَ',
  'Ana Ahmad min Almanya, wa ana Bilal min Pakistan',
  'I am Ahmed from Germany, and I am Bilal from Pakistan',
  'I am Ahmed from Germany, and I am Bilal from Pakistan',
  'Я Ахмед из Германии, а я Биляль из Пакистана',
  'audio_mcq',
  '/audio/tuhfa/bilad.mp3',
  '[{"id": "opt1", "text": "أَنَا أَحْمَدُ مِنْ أَلْمَانْيَا، وَأَنَا بِلَالٌ مِنْ بَاكِسْتَانَ", "transliteration": "Ana Ahmad min Almanya, wa ana Bilal min Pakistan", "text_en": "I am Ahmed from Germany, and I am Bilal from Pakistan", "text_ru": "Я Ахмед из Германии, а я Биляль из Пакистана"}, {"id": "opt2", "text": "أَنَا مِنْ مِصْرَ وَهُوَ مِنْ فَرَنْسَا", "transliteration": "Ana min Misr wa huwa min Faransa", "text_en": "I am from Egypt and he is from France", "text_ru": "Я из Египта, а он из Франции"}, {"id": "opt3", "text": "أَنَا رُوسِيٌّ وَهُوَ تُرْكِيٌّ", "transliteration": "Ana rusiyy wa huwa turkiyy", "text_en": "I am Russian and he is Turkish", "text_ru": "Я русский, а он турок"}, {"id": "opt4", "text": "أَنَا أُسْتَاذٌ وَهُوَ طَبِيبٌ", "transliteration": "Ana ustadh", "text_en": "I am a professor", "text_ru": "Я преподаватель"}]'::jsonb,
  'opt1',
  'في حوار التحفة الأزهرية (ص 18): أحمد من ألمانيا، وبلال من باكستان، والتقيا في القاهرة بالأزهر الشريف.',
  'في حوار التحفة الأزهرية (ص 18): أحمد من ألمانيا، وبلال من باكستان، والتقيا في القاهرة بالأزهر الشريف.',
  'In Al-Tuhfa Dialogue (p. 18): Ahmed is from Germany, Bilal is from Pakistan.',
  'В диалоге книги «Ат-Тухфа» (стр. 18): Ахмед из Германии, а Биляль из Пакистана.',
  3
);