INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'التمهيد: الأصوات الهجائية والتهيئة المصورة', 'التمهيد: الأصوات الهجائية والتهيئة المصورة', 'Prep: Alphabet Phonics & Visual Drill', 'Введение: Алфавит и звуковые иллюстрации', 'عائلة الحروف الهجائية، مخارج الحروف، الحركات القصيرة والطويلة، والتهيئة المصورة', 'عائلة الحروف الهجائية، مخارج الحروف، الحركات القصيرة والطويلة، والتهيئة المصورة', 'Arabic alphabet family, letter exits, short/long vowels, and illustrated phonetic introduction.', 'Алфавит, артикуляция звуков, краткие и долгие гласные, иллюстрированное введение.', 0);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000001', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الأَوَّلُ: تَحِيَّةٌ وَتَعَارُفٌ', 'الدَّرْسُ الأَوَّلُ: تَحِيَّةٌ وَتَعَارُفٌ', 'Lesson 1: Greetings & Introductions', 'Урок 1: Приветствие и знакомство', 'حوار التعارف في الأزهر الشريف، حرفا الألف والباء، وأسماء الإشارة (هذا / هذه)', 'حوار التعارف في الأزهر الشريف، حرفا الألف والباء، وأسماء الإشارة (هذا / هذه)', 'Meeting at Al-Azhar, letters Alif & Baa, demonstrative pronouns (Hatha / Hathihi).', 'Знакомство в Аль-Азхаре, буквы Алиф и Ба, указательные местоимения (Хаза / Хазихи).', 1);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000002', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الثَّانِي: الأُسْرَةُ', 'الدَّرْسُ الثَّانِي: الأُسْرَةُ', 'Lesson 2: The Family', 'Урок 2: Семья', 'حوار الأسرة وإعداد الغداء، حرفا التاء والثاء، التاء المربوطة، وأدوات الاستفهام (هل / ما)', 'حوار الأسرة وإعداد الغداء، حرفا التاء والثاء، التاء المربوطة، وأدوات الاستفهام (هل / ما)', 'Family & lunch preparation, letters Taa & Thaa, Ta-marbuta, question tools (Hal / Ma).', 'Семья и обед, буквы Та и Са, Та-марбута, вопросительные частицы (Халь / Ма).', 2);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000003', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الثَّالِثُ: السَّكَنُ', 'الدَّرْسُ الثَّالِثُ: السَّكَنُ', 'Lesson 3: Housing & The Home', 'Урок 3: Жилье и дом', 'البيت والغرف والأثاث، حرفا الجيم والحاء، ضمائر المتكلم والمخاطب (أنا / أنت)', 'البيت والغرف والأثاث، حرفا الجيم والحاء، ضمائر المتكلم والمخاطب (أنا / أنت)', 'Rooms, furniture, letters Jeem & Haa, subject pronouns (Ana / Anta).', 'Дом, комнаты, мебель, буквы Джим и Ха, местоимения (Ана / Анта).', 3);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000004', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الرَّابِعُ: مَعْهَدِي', 'الدَّرْسُ الرَّابِعُ: مَعْهَدِي', 'Lesson 4: My Institute', 'Урок 4: Мой институт', 'المعهد الأزهري والفصول المدرسية والأدوات، حرفا الخاء والدال، وأدوات التشبيه والوصف', 'المعهد الأزهري والفصول المدرسية والأدوات، حرفا الخاء والدال، وأدوات التشبيه والوصف', 'Classrooms, study tools, letters Khaa & Dal, descriptive structures.', 'Классы, учебные принадлежности, буквы Ха и Даль, описательные конструкции.', 4);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000005', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الخَامِسُ: الحَيَوَانَاتُ', 'الدَّرْسُ الخَامِسُ: الحَيَوَانَاتُ', 'Lesson 5: Animals', 'Урок 5: Животные', 'حيوانات المزرعة والبيئة، حرفا الذال والراء، التمييز بين المذكر والمؤنث', 'حيوانات المزرعة والبيئة، حرفا الذال والراء، التمييز بين المذكر والمؤنث', 'Domestic animals, letters Thal & Raa, masculine vs feminine nouns.', 'Животные, буквы Заль и Ра, различие мужского и женского рода.', 5);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000006', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ السَّادِسُ: الطُّيُورُ', 'الدَّرْسُ السَّادِسُ: الطُّيُورُ', 'Lesson 6: Birds', 'Урок 6: Птицы', 'عالم الطيور وأسماؤها وصفاتها، حرفا الزاي والسين، حروف الجر الأساسية', 'عالم الطيور وأسماؤها وصفاتها، حرفا الزاي والسين، حروف الجر الأساسية', 'Birds, traits, letters Zay & Seen, core prepositions (fee, 'ala, min, ila).', 'Птицы, их свойства, буквы Зай и Син, основные предлоги.', 6);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000007', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ السَّابِعُ: وَسَائِلُ المَوَاصَلَاتِ', 'الدَّرْسُ السَّابِعُ: وَسَائِلُ المَوَاصَلَاتِ', 'Lesson 7: Transportation', 'Урок 7: Транспорт', 'الحافلة، القطار، السيارة، حرفا الشين والصاد، السؤال عن المكان والتوجيهات (أين)', 'الحافلة، القطار، السيارة، حرفا الشين والصاد، السؤال عن المكان والتوجيهات (أين)', 'Bus, train, car, letters Sheen & Saad, spatial queries (Ayna / Where).', 'Транспорт (автобус, поезд, авто), буквы Шин и Сад, вопрос о месте (Айна).', 7);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000008', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الثَّامِنُ: فِي الفُنْدُقِ', 'الدَّرْسُ الثَّامِنُ: فِي الفُنْدُقِ', 'Lesson 8: At the Hotel', 'Урок 8: В гостинице', 'حجز الغرفة والخدمات الفندقية، حرفا الضاد والطاء، صيغ الطلب المؤدب (من فضلك / أريد)', 'حجز الغرفة والخدمات الفندقية، حرفا الضاد والطاء، صيغ الطلب المؤدب (من فضلك / أريد)', 'Room booking & hospitality, letters Daad & Taa, polite requests.', 'Бронирование номеров и сервис, буквы Дад и Та, вежливые просьбы.', 8);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000009', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ التَّاسِعُ: المَطَارُ وَالجَوَازَاتُ', 'الدَّرْسُ التَّاسِعُ: المَطَارُ وَالجَوَازَاتُ', 'Lesson 9: Airport & Passports', 'Урок 9: Аэропорт и паспорта', 'إجراءات السفر والتأشيرة، حرفا الظاء والعين، السؤال عن المواعيد والأزمنة (متى)', 'إجراءات السفر والتأشيرة، حرفا الظاء والعين، السؤال عن المواعيد والأزمنة (متى)', 'Travel formalities, luggage, letters Dhaa & 'Ayn, timing inquiries (Mata / When).', 'Паспортный контроль и багаж, буквы За и Айн, вопрос времени (Мата).', 9);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000010', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ العَاشِرُ: جِسْمُ الإِنْسَانِ', 'الدَّرْسُ العَاشِرُ: جِسْمُ الإِنْسَانِ', 'Lesson 10: The Human Body', 'Урок 10: Тело человека', 'أعضاء الجسم والحواس، حرفا الغين والفاء، التعبير عن المشاعر والصحة والألم', 'أعضاء الجسم والحواس، حرفا الغين والفاء، التعبير عن المشاعر والصحة والألم', 'Body parts, senses, letters Ghayn & Faa, health & physical feelings.', 'Части тела, чувства, буквы Гайн и Фа, самочувствие и здоровье.', 10);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000011', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الحَادِي عَشَرَ: المَلَابِسُ', 'الدَّرْسُ الحَادِي عَشَرَ: المَلَابِسُ', 'Lesson 11: Clothing & Attire', 'Урок 11: Одежда', 'الملابس الصيفية والشتوية، حرفا القاف والكاف، أسماء الألوان وتطابق الصفة والموصوف', 'الملابس الصيفية والشتوية، حرفا القاف والكاف، أسماء الألوان وتطابق الصفة والموصوف', 'Clothes, seasonal wear, letters Qaaf & Kaaf, colors and adjective agreements.', 'Одежда по сезонам, буквы Каф и Кяф, цвета и согласование прилагательных.', 11);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000012', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الثَّانِي عَشَرَ: فِي السُّوقِ', 'الدَّرْسُ الثَّانِي عَشَرَ: فِي السُّوقِ', 'Lesson 12: In the Market', 'Урок 12: На рынке', 'التسوق والشراء والأسعار، حرفا اللام والميم، السؤال عن الثمن والمقادير (بكم / كم)', 'التسوق والشراء والأسعار، حرفا اللام والميم، السؤال عن الثمن والمقادير (بكم / كم)', 'Shopping, prices, letters Laam & Meem, price and quantity questions (Bikam / Kam).', 'Покупки и цены, буквы Лям и Мим, вопрос стоимости и количества (Бикам / Кам).', 12);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000013', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الثَّالِثُ عَشَرَ: خَضْرَاوَاتٌ وَفَوَاكِهُ', 'الدَّرْسُ الثَّالِثُ عَشَرَ: خَضْرَاوَاتٌ وَفَوَاكِهُ', 'Lesson 13: Vegetables & Fruits', 'Урок 13: Овощи и фрукты', 'أنواع الخضار والفواكه، حرفا النون والهاء، التفضيل والأطعمة المفضلة (أحب / أفضل)', 'أنواع الخضار والفواكه، حرفا النون والهاء، التفضيل والأطعمة المفضلة (أحب / أفضل)', 'Vegetables, fruits, letters Noon & Haa, expressing food preferences (Uhibbu).', 'Овощи и фрукты, буквы Нун и Ха, предпочтения в еде (Ухиббу).', 13);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000014', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الرَّابِعُ عَشَرَ: الأَصْدِقَاءُ', 'الدَّرْسُ الرَّابِعُ عَشَرَ: الأَصْدِقَاءُ', 'Lesson 14: Friends & Fellowship', 'Урок 14: Друзья', 'حوارات الصداقة والزيارة، حرف الواو والياء، ضمائر الغائب (هو / هي / هم)', 'حوارات الصداقة والزيارة، حرف الواو والياء، ضمائر الغائب (هو / هي / هم)', 'Friendship, visiting companions, letters Waw & Yaa, 3rd person pronouns (Huwa / Hiya).', 'Дружба, визиты, буквы Вав и Йа, местоимения 3-го лица (Хува / Хийя).', 14);
INSERT INTO units (id, level_id, title, title_ar, title_en, title_ru, description, description_ar, description_en, description_ru, order_index)
VALUES ('10000000-0000-0000-0000-000000000015', '11111111-1111-1111-1111-111111111111', 'الدَّرْسُ الخَامِسُ عَشَرَ: النَّادِي', 'الدَّرْسُ الخَامِسُ عَشَرَ: النَّادِي', 'Lesson 15: Sports & The Club', 'Урок 15: Клуб и спорт', 'الرياضة والأنشطة والترويح عن النفس، مراجعة الأصوات والتراكيب العامة للمستوى الأول', 'الرياضة والأنشطة والترويح عن النفس، مراجعة الأصوات والتراكيب العامة للمستوى الأول', 'Sports, activities, hobbies, comprehensive review of Book 1 phonics and syntax.', 'Спорт, активности, хобби, итоговое повторение фонетики и конструкций Книги 1.', 15);